/**
 * mockData.js — High-quality fallback data for the travel app.
 */

export const MOCK_DESTINATIONS = [
  {
    id: 1,
    name: 'Santorini',
    country: 'Greece',
    image: 'https://images.wallpapersden.com/image/download/santorini-island-greece_bGlqZmiUmZqaraWkpJRpZWllrWdnZms.jpg',
    description: 'Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape.',
    rating: 4.9,
    climate: 'Mediterranean',
    currency: 'Euro (EUR)',
    language: 'Greek',
    cost_of_living: 'High',
    best_time_to_visit: 'April to October',
    popular_for: ['Sunsets', 'White Buildings', 'Blue Domes', 'Volcanic Beaches'],
  },
  {
    id: 2,
    name: 'Kyoto',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8a3lvdG98ZW58MHx8MHx8fDA%3D',
    description: 'Kyoto, once the capital of Japan, is a city on the island of Honshu. It is famous for its numerous classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines and traditional wooden houses.',
    rating: 4.8,
    climate: 'Temperate',
    currency: 'Yen (JPY)',
    language: 'Japanese',
    cost_of_living: 'Moderate',
    best_time_to_visit: 'March to May (Cherry Blossoms)',
    popular_for: ['Temples', 'Geisha Culture', 'Gardens', 'History'],
  },
  {
    id: 3,
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://wallpapers.com/images/featured/bali-qhidusvhukn25lb1.jpg',
    description: 'Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple.',
    rating: 4.7,
    climate: 'Tropical',
    currency: 'Rupiah (IDR)',
    language: 'Indonesian',
    cost_of_living: 'Low',
    best_time_to_visit: 'April to September',
    popular_for: ['Surfing', 'Yoga', 'Rice Terraces', 'Beaches'],
  },
  {
    id: 4,
    name: 'Paris',
    country: 'France',
    image: 'https://4kwallpapers.com/images/walls/thumbs_3t/3332.jpg',
    description: 'Paris, France’s capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine.',
    rating: 4.6,
    climate: 'Oceanic',
    currency: 'Euro (EUR)',
    language: 'French',
    cost_of_living: 'Very High',
    best_time_to_visit: 'June to August',
    popular_for: ['Eiffel Tower', 'Louvre Museum', 'Fashion', 'Cuisine'],
  },
  {
    id: 5,
    name: 'Amalfi Coast',
    country: 'Italy',
    image: 'https://images.unsplash.com/photo-1633321088390-802ba85fbc40?auto=format&fit=crop&q=80&w=800',
    description: 'The Amalfi Coast is a 50-kilometer stretch of coastline along the southern edge of Italy’s Sorrentine Peninsula, in the Campania region. It’s a popular holiday destination, with sheer cliffs and a rugged shoreline dotted with small beaches.',
    rating: 4.9,
    climate: 'Mediterranean',
    currency: 'Euro (EUR)',
    language: 'Italian',
    cost_of_living: 'High',
    best_time_to_visit: 'May to September',
    popular_for: ['Cliffside Villages', 'Limoncello', 'Scenic Views', 'Beaches'],
  },
  {
    id: 6,
    name: 'Banff National Park',
    country: 'Canada',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800',
    description: 'Banff National Park is Canada’s oldest national park, nestled in the Rocky Mountains. It’s celebrated for its turquoise glacial lakes, abundant wildlife, and endless outdoor adventures.',
    rating: 4.9,
    climate: 'Subarctic',
    currency: 'CAD',
    language: 'English',
    cost_of_living: 'Moderate',
    best_time_to_visit: 'June to August & Dec to March',
    popular_for: ['Hiking', 'Skiing', 'Lake Louise', 'Wildlife'],
  },
  {
    id: 7,
    name: 'Maui',
    country: 'USA',
    image: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&q=80&w=800',
    description: 'The island of Maui is a destination for true nature lovers. Known as the "Valley Isle," it features the stunning Road to Hana, sunrise views at Haleakala, and world-class snorkeling.',
    rating: 4.8,
    climate: 'Tropical',
    currency: 'USD',
    language: 'English',
    cost_of_living: 'High',
    best_time_to_visit: 'April to May & Sept to Nov',
    popular_for: ['Road to Hana', 'Snorkeling', 'Whale Watching', 'Beaches'],
  },
  {
    id: 8,
    name: 'Cape Town',
    country: 'South Africa',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&q=80&w=800',
    description: 'Cape Town is a port city on South Africa’s southwest coast, on a peninsula beneath the imposing Table Mountain. It offers a mix of stunning coastlines, rich history, and nearby winelands.',
    rating: 4.7,
    climate: 'Mediterranean',
    currency: 'Rand (ZAR)',
    language: 'English, Afrikaans',
    cost_of_living: 'Low',
    best_time_to_visit: 'January to April',
    popular_for: ['Table Mountain', 'Penguins', 'Wine Tasting', 'Safaris'],
  },
  {
    id: 9,
    name: 'Machu Picchu',
    country: 'Peru',
    image: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&q=80&w=800',
    description: 'Machu Picchu is an Incan citadel set high in the Andes Mountains in Peru. Built in the 15th century and later abandoned, it’s renowned for its sophisticated dry-stone walls and panoramic views.',
    rating: 4.9,
    climate: 'Subtropical',
    currency: 'Sol (PEN)',
    language: 'Spanish',
    cost_of_living: 'Low',
    best_time_to_visit: 'May to October',
    popular_for: ['Inca Trail', 'Ancient Ruins', 'Mountain Views', 'History'],
  },
  {
    id: 10,
    name: 'Reykjavik',
    country: 'Iceland',
    image: 'https://images.unsplash.com/photo-1516834474-48c0abc2a902?auto=format&fit=crop&q=80&w=800',
    description: 'Reykjavik, on the coast of Iceland, is the country\'s capital and largest city. It’s a gateway to dramatic landscapes involving volcanoes, geysers, hot springs, and lava fields.',
    rating: 4.8,
    climate: 'Subpolar Oceanic',
    currency: 'Krona (ISK)',
    language: 'Icelandic',
    cost_of_living: 'Very High',
    best_time_to_visit: 'June to August (Midnight Sun)',
    popular_for: ['Northern Lights', 'Blue Lagoon', 'Waterfalls', 'Geysers'],
  },
  {
    id: 11,
    name: 'Maldives',
    country: 'Maldives',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&q=80&w=800',
    description: 'The Maldives is a tropical nation in the Indian Ocean composed of 26 ring-shaped atolls. It’s famous for its beaches, blue lagoons, extensive reefs, and luxurious overwater bungalows.',
    rating: 4.9,
    climate: 'Tropical',
    currency: 'Rufiyaa (MVR)',
    language: 'Dhivehi',
    cost_of_living: 'Very High',
    best_time_to_visit: 'November to April',
    popular_for: ['Overwater Villas', 'Scuba Diving', 'Honeymoons', 'Coral Reefs'],
  },
  {
    id: 12,
    name: 'Rome',
    country: 'Italy',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=800',
    description: 'Rome is the capital city of Italy and a special comune. Known as the Eternal City, it is steeped in nearly 3,000 years of globally influential art, architecture, and culture.',
    rating: 4.7,
    climate: 'Mediterranean',
    currency: 'Euro (EUR)',
    language: 'Italian',
    cost_of_living: 'Moderate',
    best_time_to_visit: 'April to June & Sept to Oct',
    popular_for: ['The Colosseum', 'Vatican City', 'Pasta', 'Ancient History'],
  },
  {
    id: 13,
    name: 'Queenstown',
    country: 'New Zealand',
    image: 'https://images.unsplash.com/photo-1607686817124-738cb20d20d7?auto=format&fit=crop&q=80&w=800',
    description: 'Queenstown sits on the shores of the South Island’s Lake Wakatipu, set against the dramatic Southern Alps. It’s renowned for adventure sports and serves as a base for exploring the region’s vineyards.',
    rating: 4.8,
    climate: 'Oceanic',
    currency: 'NZD',
    language: 'English',
    cost_of_living: 'High',
    best_time_to_visit: 'December to February (Summer)',
    popular_for: ['Bungee Jumping', 'Skiing', 'Fjords', 'Wine'],
  },
  {
    id: 14,
    name: 'Dubai',
    country: 'UAE',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&q=80&w=800',
    description: 'Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture, and a lively nightlife scene. Burj Khalifa dominates the skyscraper-filled skyline.',
    rating: 4.6,
    climate: 'Desert',
    currency: 'Dirham (AED)',
    language: 'Arabic, English',
    cost_of_living: 'High',
    best_time_to_visit: 'November to March',
    popular_for: ['Burj Khalifa', 'Luxury Shopping', 'Desert Safaris', 'Architecture'],
  },
  {
    id: 15,
    name: 'Petra',
    country: 'Jordan',
    image: 'https://images.unsplash.com/photo-1501231454556-9dcfb18af4d6?auto=format&fit=crop&q=80&w=800',
    description: 'Petra is a famous archaeological site in Jordan\'s southwestern desert. Dating to around 300 B.C., it was the capital of the Nabatean Kingdom and is accessed via a narrow canyon called Al Siq.',
    rating: 4.8,
    climate: 'Desert',
    currency: 'Dinar (JOD)',
    language: 'Arabic',
    cost_of_living: 'Moderate',
    best_time_to_visit: 'March to May & Sept to Nov',
    popular_for: ['The Treasury', 'Ancient Ruins', 'Desert Treks', 'History'],
  }
];