/**
 * mockData.js — High-quality fallback data for the travel app.
 * If the external API is unreachable, this data ensures the app
 * remains functional and visually appealing.
 */

export const MOCK_DESTINATIONS = [
  {
    id: 1,
    name: 'Santorini',
    country: 'Greece',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&q=80&w=800',
    description: 'Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape.',
    rating: 4.9,
    climate: 'Mediterranean',
    currency: 'Euro (EUR)',
    language: 'Greek',
    cost_of_living: 'High',
    best_time_to_visit: 'April to October',
    popular_for: ['Sunsets', 'White Buildings', 'Blue Domes', 'Volcanic Beaches'],
  },
  {
    id: 2,
    name: 'Kyoto',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=800',
    description: 'Kyoto, once the capital of Japan, is a city on the island of Honshu. It is famous for its numerous classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines and traditional wooden houses.',
    rating: 4.8,
    climate: 'Temperate',
    currency: 'Yen (JPY)',
    language: 'Japanese',
    cost_of_living: 'Moderate',
    best_time_to_visit: 'March to May (Cherry Blossoms)',
    popular_for: ['Temples', 'Geisha Culture', 'Gardens', 'History'],
  },
  {
    id: 3,
    name: 'Bali',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&q=80&w=800',
    description: 'Bali is an Indonesian island known for its forested volcanic mountains, iconic rice paddies, beaches and coral reefs. The island is home to religious sites such as cliffside Uluwatu Temple.',
    rating: 4.7,
    climate: 'Tropical',
    currency: 'Rupiah (IDR)',
    language: 'Indonesian',
    cost_of_living: 'Low',
    best_time_to_visit: 'April to September',
    popular_for: ['Surfing', 'Yoga', 'Rice Terraces', 'Beaches'],
  },
  {
    id: 4,
    name: 'Paris',
    country: 'France',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=800',
    description: 'Paris, France’s capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine.',
    rating: 4.6,
    climate: 'Oceanic',
    currency: 'Euro (EUR)',
    language: 'French',
    cost_of_living: 'Very High',
    best_time_to_visit: 'June to August',
    popular_for: ['Eiffel Tower', 'Louvre Museum', 'Fashion', 'Cuisine'],
  },
  {
    id: 5,
    name: 'Amalfi Coast',
    country: 'Italy',
    image: 'https://images.unsplash.com/photo-1633321088390-802ba85fbc40?auto=format&fit=crop&q=80&w=800',
    description: 'The Amalfi Coast is a 50-kilometer stretch of coastline along the southern edge of Italy’s Sorrentine Peninsula, in the Campania region. It’s a popular holiday destination, with sheer cliffs and a rugged shoreline dotted with small beaches and pastel-colored fishing villages.',
    rating: 4.9,
    climate: 'Mediterranean',
    currency: 'Euro (EUR)',
    language: 'Italian',
    cost_of_living: 'High',
    best_time_to_visit: 'May to September',
    popular_for: ['Cliffside Villages', 'Limoncello', 'Scenic Views', 'Beaches'],
  },
];
